# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Crafty Amanda
# A short tagline that appears below the title in site masthead.
# subtitle:
name: &name Amanda Watson
email: amanda@craftyamanda.com
description: &description >- # this means to ignore newlines until the next YAML element
  A carefully compiled compendium of crafty components
# logo: "/assets/images/logo-88x88.png"
# For pages that don’t have a header.image assigned in their YAML Front Matter, site.og_image will be used as a
# fallback during social sharing. Use your logo, icon, avatar or something else that is meaningful. Just make sure it
# is placed in the /assets/images/ folder, has a minimum size of 120px by 120px, and is less than 1MB in file size.
# og_image: /assets/images/site-logo.png
# twitter_username: username
# github_username: username
minimal_mistakes_skin: default
search: true
domain: www.craftyamanda.com
url: "https://www.craftyamanda.com" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog

# social:
#   type:  # Person or Organization (defaults to Person)
#   name:  # If the user or organization name differs from the site's name
#   links:
#     - "https://twitter.com/yourTwitter"
#     - "https://www.facebook.com/yourFacebook"
#     - "https://instagram.com/yourProfile"
#     - "https://www.linkedin.com/in/yourprofile"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "America/New_York"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .jekyll-cache/
  - .ruby-version
  - .sass-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : *name
  avatar : "/assets/images/bio-photo.jpg"
  bio    : *description
  location: Atlanta
  links:
    - label: "amanda@craftyamanda.com"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:amanda@craftyamanda.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/watson81/craftyamanda.com"
    - label: "Patrick's Website"
      icon: "fas fa-fw fa-user-cog"
      url: "https://www.patrickwatson.org"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      show_date: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/



# These settings are hardcoded by github pages.
# See https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
